### ISSUE TITLE
Mobile friendly

### ISSUE THREAD

**Issue by dmayfieldjones** [habeducation/habeducation.github.io#27]
Still observing overlapping words and image scaling issues on mobile. I think it is still worth fixing at some point.

**Comment by htruong** [comment]
I see two issues on mobile right now that needs fixed:

The data page is not displaying correctly.

The menu is not displaying correctly.

The menu is more high priority.

**Comment by cmdcolin** [comment]
Probably gotta make a hamburger menu or similar for mobile. lots of items in header bar

**Comment by htruong** [comment]
Mobile menu is quasi-fixed. It is now scrollable to the right, so if someone wants to scroll right to get to the other pages, they can. I'm not too happy but we can also add hints that there is more stuff on the right. 

I personally prefer to be able to see the menu right out instead of having to press the hamburger menu to see, less discoverable.

**Comment by htruong** [comment]
Seems like it's fixed now!
